### ISSUE TITLE
/usr/local/jamoma/* folders creation problem

### ISSUE THREAD

**Issue by reno-** [i-score-old/Score-old#2]
These folders cannot be create when I build Score, so nothing is copied inside these folders.
extensions
includes
lib

Solution : Create manually these folders

**Comment by theod** [comment]
yes. this is explained inside the Readme.txt as I don't know the ruby command to create it automatically.
maybe someone knows how to do this quickly ?

**Comment by jln-** [comment]
This should be fixed on dev branch. Can you confirm ?

**Comment by reno-** [comment]
I just say Bravo !!
